export enum ArtworkStyle {
  IMPRESSIONISM          = 'Impressionism',
  POST_IMPRESSIONISM     = 'Post-Impressionism',
  REALISM                = 'Realism',
  NATURALISM             = 'Naturalism',
  CUBISM                 = 'Cubism',
  ABSTRACT               = 'Abstract',
  ABSTRACT_EXPRESSIONISM = 'Abstract Expressionism',
  EXPRESSIONISM          = 'Expressionism',
  SURREALISM             = 'Surrealism',
  FAUVISM                = 'Fauvism',
  POP_ART                = 'Pop Art',
  MINIMALISM             = 'Minimalism',
  BAROQUE                = 'Baroque',
  RENAISSANCE            = 'Renaissance',
  ROMANTICISM            = 'Romanticism',
  NEOCLASSICISM          = 'Neoclassicism',
  ART_NOUVEAU            = 'Art Nouveau',
  ART_DECO               = 'Art Deco',
  SYMBOLISM              = 'Symbolism',
  MODERNISM              = 'Modernism',
  CONTEMPORARY           = 'Contemporary',
  GOTHIC                 = 'Gothic',
  MANNERISM              = 'Mannerism',
  ROCOCO                 = 'Rococo',
  POINTILLISM            = 'Pointillism',
}
