import { ArtworkType } from './artwork-type.enum';
import { ArtworkStyle } from './artwork-style.enum';

export const ARTWORK_TYPE_OPTIONS = [
  { value: ArtworkType.PAINTING,        label: 'Peinture' },
  { value: ArtworkType.SCULPTURE,       label: 'Sculpture' },
  { value: ArtworkType.DRAWING,         label: 'Dessin' },
  { value: ArtworkType.WATERCOLOR,      label: 'Aquarelle' },
  { value: ArtworkType.PASTEL,          label: 'Pastel' },
  { value: ArtworkType.PHOTOGRAPHY,     label: 'Photographie' },
  { value: ArtworkType.PRINT,           label: 'Estampe / Gravure' },
  { value: ArtworkType.COLLAGE,         label: 'Collage' },
  { value: ArtworkType.MIXED_MEDIA,     label: 'Techniques mixtes' },
  { value: ArtworkType.INSTALLATION,    label: 'Installation' },
  { value: ArtworkType.VIDEO,           label: 'Vidéo / Film' },
  { value: ArtworkType.TEXTILE,         label: 'Textile' },
  { value: ArtworkType.CERAMICS,        label: 'Céramique' },
  { value: ArtworkType.METALWORK,       label: 'Travail du métal' },
  { value: ArtworkType.GLASS,           label: 'Verre' },
  { value: ArtworkType.JEWELRY,         label: 'Bijouterie / Joaillerie' },
  { value: ArtworkType.FURNITURE,       label: 'Mobilier' },
  { value: ArtworkType.DECORATIVE_ARTS, label: 'Arts décoratifs' },
  { value: ArtworkType.ARCHITECTURE,    label: 'Architecture' },
  { value: ArtworkType.BOOK,            label: 'Livre / Manuscrit' },
];

export const ARTWORK_STYLE_OPTIONS = [
  { value: ArtworkStyle.IMPRESSIONISM,          label: 'Impressionnisme' },
  { value: ArtworkStyle.POST_IMPRESSIONISM,     label: 'Post-impressionnisme' },
  { value: ArtworkStyle.REALISM,                label: 'Réalisme' },
  { value: ArtworkStyle.NATURALISM,             label: 'Naturalisme' },
  { value: ArtworkStyle.ROMANTICISM,            label: 'Romantisme' },
  { value: ArtworkStyle.NEOCLASSICISM,          label: 'Néoclassicisme' },
  { value: ArtworkStyle.BAROQUE,                label: 'Baroque' },
  { value: ArtworkStyle.ROCOCO,                 label: 'Rococo' },
  { value: ArtworkStyle.RENAISSANCE,            label: 'Renaissance' },
  { value: ArtworkStyle.GOTHIC,                 label: 'Gothique' },
  { value: ArtworkStyle.MANNERISM,              label: 'Maniérisme' },
  { value: ArtworkStyle.SYMBOLISM,              label: 'Symbolisme' },
  { value: ArtworkStyle.ART_NOUVEAU,            label: 'Art Nouveau' },
  { value: ArtworkStyle.ART_DECO,               label: 'Art Déco' },
  { value: ArtworkStyle.FAUVISM,                label: 'Fauvisme' },
  { value: ArtworkStyle.CUBISM,                 label: 'Cubisme' },
  { value: ArtworkStyle.EXPRESSIONISM,          label: 'Expressionnisme' },
  { value: ArtworkStyle.ABSTRACT,               label: 'Abstrait' },
  { value: ArtworkStyle.ABSTRACT_EXPRESSIONISM, label: 'Expressionnisme abstrait' },
  { value: ArtworkStyle.SURREALISM,             label: 'Surréalisme' },
  { value: ArtworkStyle.POP_ART,                label: 'Pop Art' },
  { value: ArtworkStyle.MINIMALISM,             label: 'Minimalisme' },
  { value: ArtworkStyle.POINTILLISM,            label: 'Pointillisme' },
  { value: ArtworkStyle.MODERNISM,              label: 'Modernisme' },
  { value: ArtworkStyle.CONTEMPORARY,           label: 'Art contemporain' },
];
