export enum ArtworkType {
  PAINTING        = 'Painting',
  SCULPTURE       = 'Sculpture',
  DRAWING         = 'Drawing',
  PHOTOGRAPHY     = 'Photography',
  PRINT           = 'Print',
  TEXTILE         = 'Textile',
  DECORATIVE_ARTS = 'Decorative Arts',
  CERAMICS        = 'Ceramics',
  METALWORK       = 'Metalwork',
  GLASS           = 'Glass',
  JEWELRY         = 'Jewelry',
  FURNITURE       = 'Furniture',
  INSTALLATION    = 'Installation',
  VIDEO           = 'Video',
  BOOK            = 'Book',
  ARCHITECTURE    = 'Architecture',
  MIXED_MEDIA     = 'Mixed Media',
  COLLAGE         = 'Collage',
  WATERCOLOR      = 'Watercolor',
  PASTEL          = 'Pastel',
}
